version: '3.3'

networks:
  transcendence_network:

services:
  nginx:
    container_name: nginx
    image: nginx
    restart: always
    depends_on:
      - nestjs
    build:
      context: backend/nginx
    networks:
      - transcendence_network
    ports:
      - 8080:80

  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE}
      TZ: ${DB_TIMEZONE}
    networks:
      - transcendence_network
    ports:
      - ${DB_PORT}:5432

  nestjs:
    container_name: nestjs
    image: nestjs
    restart: always
    depends_on:
      - postgres
    env_file:
      - .env
    build:
      context: backend/nestjs
      dockerfile: ${BUILD_ENVIROMENT}
    networks:
      - transcendence_network

  react:
    container_name: react
    image: react
    restart: always
    depends_on:
      - nestjs
    env_file:
      - .env
    build:
      context: frontend/react
    ports:
      - 3001:3001
